### ISSUE TITLE
Plugin doesn't work anymore

### ISSUE THREAD

**Issue by Saidelocha** [nicdun/logseq-kindle-import#148]
Hello,

The plugin doesn't work anymore.
The data extracted are useless. 
You can see by yourself the .md created with your plugin and the html of my hightlights on the book of tiago forte.

Thanks for your help and your plugin ;)

[Book___Tiago Forte - Building a Second Brain _ A Proven Method to Organize Your Digital Life and Unlock Your Creative Potential (2022, Atria Books) - libgen.li.md](https://github.com/nicdun/logseq-kindle-import/files/11901966/Book___Tiago.Forte.-.Building.a.Second.Brain._.A.Proven.Method.to.Organize.Your.Digital.Life.and.Unlock.Your.Creative.Potential.2022.Atria.Books.-.libgen.li.md)

**Comment by nicdun** [comment]
hey, the plugin works - you need to export your highlights as a html file, not a markdown file.
