### ISSUE TITLE
Kindle plugin is not working for windows LogSeq

### ISSUE THREAD

**Issue by BrunoZluhan** [nicdun/logseq-kindle-import#214]
Hi, I tried to install the Kindle highlight import but didn't work. The message I got asked to share the following into this coment:

[Error]<logseq-kindle-import> :release-channel-issue "Github API Failed(403) {\"message\":\"API rate limit exceeded for user ID 1779837. If you reach out to GitHub Support for help, please include the request ID 2594:1129E:43AA709:444CF1A:65143EF4.\",\"documentation_url\":\"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"}"]

**Comment by felipeeler** [comment]
Does it work on mac os or linux?

**Comment by nicdun** [comment]
It's working on all platforms - the issue mentioned in the ticket is based on some github api limits. Didn't get further information about that. Feel free to use the plugin and give feedback!
